<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

class BaseController extends Controller{
    public $enableCsrfValidation = false;

    public function beforeAction($action)
    {
        $data = json_decode(file_get_contents("php://input"),true);
        if($data != null){
            foreach($data as $key=>$value){
                $_POST[$key]=$value;
            }
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}

